version: "2"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: <username>
      MONGO_INITDB_ROOT_PASSWORD: <password>
  node:
    image: "node:14"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - "3500:3500"
    restart: always
    command: "npm start"